### ISSUE TITLE
Configuring with EDI input - strange warning message

### ISSUE THREAD

**Issue by andimik** [Opendigitalradio/ODR-DabMod#36] opened 2019-09-09 19:07 UTC
Using latest next branch.

When I configure it without parameter, EDI seems to be disabled:

`$ ./configure --disable-output-uhd`

```
  Features
  Enabled:  zeromq soapysdr
  Disabled:  edi prof trace output_uhd easydabv3
```
So I have changed to 

`$ ./configure --disable-output-uhd --enable-edi`

then EDI seems to be configured, but the warning message is strange.

```
configure: WARNING: unrecognized options: --enable-edi

***********************************************

  Features
  Enabled:  edi zeromq soapysdr
  Disabled:  prof trace output_uhd easydabv3

```

**Comment by mpbraendli** [comment] 2019-09-13 17:07
Hi, thanks for the report.
The problem is actually only the printout during the configure phase. EDI is now always enabled.
Should be fixed now in ca09923

**Closed by mpbraendli** 2019-09-13 17:07 UTC
